[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[fuzz]
runs = 65536
seed = '0x2'

[invariant]
runs = 64
depth = 32
# we only care about invariants not the fuzz by doing fasle it
fail_on_revert = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
